// config.js - Configuration for language and theme settings

// Language configuration
const translations = {
    en: {
        // Header
        "appTitle": "foxfile.org",
        "appDescription": "Secure end-to-end encrypted file sharing.",
        
        // Upload section
        "shareFile": "Share File",
        "selectFilePrompt": "Click or drag to select a file",
        "selectedFile": "Selected file:",
        "shareButton": "Share File",
        "shareCode": "Share code:",
        "waitingForReceiver": "Waiting for receiver connection...",
        "receiverConnected": "Receiver connected. Exchanging keys & signals...",
        "sendingFile": "Sending file...",
        "fileSuccessfullySent": "File successfully sent to receiver!",
        "sendingProgress": "Sending {percent}%...",
        
        // Download section
        "downloadFile": "Download File",
        "enterShareCode": "Enter share code",
        "shareCodePlaceholder": "e.g. XYZ123",
        "connectAndDownload": "Connect and Download",
        "connecting": "Connecting...",
        "receivingFile": "Receiving file...",
        "transferComplete": "File transfer complete!",
        "startDownload": "Start Download",
        "downloadStarted": "Download started automatically",
        "clickToDownload": "Automatic download failed. Click button to download.",
        "fileReceivedAssembling": "File received. Assembling...",
        "downloadButtonText": "Download {filename}",
        "transferSuccessMessage": "File '{filename}' received successfully!",

        // Info section
        "howItWorks": "How It Works?",
        "step1Title": "1. File Selection & Code",
        "step1Text": "Sender selects a file. A unique share code is generated by the server.",
        "step2Title": "2. Code Sharing",
        "step2Text": "The sender shares the code with the receiver.",
        "step3Title": "3. Secure Connection",
        "step3Text": "Receiver enters the code. A secure WebSocket connection links both users via the server.",
        "step4Title": "4. Secure P2P Transfer",
        "step4Text": "Once securely connected, the encrypted file is transferred directly between devices (P2P).",
        "securityTitle": "Security",
        "securityText": "Files are encrypted directly in your browser using a securely exchanged key (AES-GCM) before transfer via WebRTC. Only the intended receiver can decrypt them. The server facilitates the connection but never sees your file content or the decryption key. Metadata (filename, size) is sent unencrypted over the secure data channel *after* connection.",
        "principleTitle": "Working Principle",
        "principleText": "You connect to our server via WebSocket using a share code to find the other peer. The server relays messages for secure key exchange (ECDH) and WebRTC connection setup (using STUN/TURN servers). Once the secure WebRTC data channel is established, the encrypted file is transferred directly peer-to-peer.",
        "technologiesTitle": "Why Donation is Needed?",
        "technologiesText": "FoxFile is developed by an independent developer and is completely free. We need your support to cover server costs and keep the project sustainable.",
        
        // Footer
        "footerText": "foxfile.org © 2025 | End-to-end encrypted, peer-to-peer file sharing application",
        
        // Notifications
        "codeCopied": "Code copied",
        "codeCreated": "Share code created",
        "pleaseSelectFile": "Please select a file",
        "invalidCodeFormat": "Invalid code format",
        "connectionError": "Connection error occurred",
        "fileReadError": "File reading error",
        "scanQrCodePrompt": "Scan to download",
        "downloadSuccessReceiver": "File downloaded successfully!",
        // E2E Crypto & Connection Status
        "generatingCode": "Generating code...",
        "connectingToSender": "Connecting to sender...",
        "codeReceivedFromUrl": "Code received from URL, connecting...",
        "keyGenerationError": "Error generating encryption keys",
        "keyExchangeError": "Error during secure key exchange",
        "keyExchangeIncomplete": "Secure connection not ready",
        "secureConnectionEstablishedSending": "Secure connection established. Preparing to send...",
        "secureConnectionEstablishedWaiting": "Secure connection established. Waiting for file...",
        "encryptionError": "File encryption error",
        "decryptionError": "File decryption error",
        "downloadSetupError": "Error preparing file for download",
        "transferError": "File transfer error",
        "receiverConnectedInitiatingKeyExchange": "Receiver connected. Starting secure key exchange...",
        "connectedToSenderInitiatingKeyExchange": "Connected to sender. Starting secure key exchange...",
        "downloadStarting": "Download starting...",
        "fileSentWaitingConfirmation": "File sent. Waiting for receiver confirmation...",
        "transferSuccessPrompt": "File sent successfully! Select another file to share again.",
        "transferStarted": "File transfer started.",
        "channelsNotReady": "Data channels not ready yet.",
        "metadataError": "Metadata processing error.",
        "sendFileError": "Cannot send file. Prerequisites not met.",
        "chunkReadSendError": "Error reading or sending file chunk.",
        "fileSentWaiting": "File sending complete. Waiting for receiver...",
        "transferAbortedChannelClose": "Transfer aborted due to channel closure.",
        "channelError": "Data channel error",
        "transferAborted": "File transfer aborted.",
        "chunkDecryptError": "Chunk decryption failed.",
        "receiveError": "Error receiving file chunk.",
        "fileAssemblyError": "Error assembling received file.",
        "connectionInterrupted": "Connection interrupted.",
        "peerConnectionError": "Peer connection setup failed.",
        
        // Popup translations
        "successTitle": "Success!",
        "okButton": "OK",
        // Donation Button
        "donateButton": "Support Us",
        "donateTooltipTitle": "If You Love This Project, You Can Support It!",
        "donateTooltipLine1": "FoxFile is developed by an independent developer and is completely free.",
        "donateTooltipLine2": "We need your support to cover server costs and keep the project sustainable.",
        
        // Connection System Accordion
        "connectionSystemTitle": "How Connections are Established",
        "connectionSystemHowTitle": "How Connection System Works?",
        "sameNetworkTitle": "On the Same Local Network (LAN):",
        "sameNetworkText": "When two computers are on the same local network (e.g., same Wi-Fi), STUN servers help discover their IP addresses, and a direct connection can typically be established easily. This process works as follows:",
        "sameNetworkStep1": "Both sender and receiver connect to our server via WebSocket.",
        "sameNetworkStep2": "The share code is used for matching.",
        "sameNetworkStep3": "Our STUN servers discover the local IP addresses of both parties.",
        "sameNetworkStep4": "WebRTC connection is established, and the file is transferred directly between peers.",
        "differentNetworkTitle": "On Different Networks:",
        "differentNetworkText": "When computers are on different networks (e.g., different locations, behind NAT or firewalls), the connection process is more complex:",
        "differentNetworkStep1": "WebSocket connection to our server and matching via share code works the same way.",
        "differentNetworkStep2": "STUN servers first try to establish a direct connection, but most NAT devices and firewalls may block this.",
        "differentNetworkStep3": "If direct connection cannot be established, our TURN servers come into play.",
        "differentNetworkStep4": "TURN servers act as a relay to bypass NAT and firewalls - communication between the two parties is relayed through these servers.",
        "differentNetworkStep5": "File transfer occurs securely and encrypted via our TURN servers.",
        "technicalDetailsTitle": "Technical Details:",
        "technicalDetailsText": "FoxFile ensures secure connections using these technologies:",
        "technicalDetailWebRTC": "WebRTC: For browser-based real-time communication",
        "technicalDetailSTUN": "STUN Servers: To discover the actual addresses of devices behind NAT",
        "technicalDetailTURN": "TURN Servers: To relay traffic when direct connection cannot be established",
        "technicalDetailDTLS": "DTLS: Transport layer security for data channel",
        "technicalDetailAES": "AES-GCM: End-to-end encryption for file contents",
        "analyticsTitle": "Analytics:",
        "analyticsText": "We use GoatCounter, which is a privacy-focused analytics tool:",
        "analyticsNoCookies": "No cookies are used",
        "analyticsAnonymous": "IPs are anonymized while still providing country-based location information",
        
        // Terms and Privacy
        "termsTitle": "Terms of Service and Privacy Policy",
        "termsOfService": "Terms of Service",
        "termsDate": "Effective Date: April 20, 2025",
        "termsPartiesTitle": "1. Parties and Acceptance",
        "termsPartiesText": "This agreement is between [Foxfile.org] ('Platform') and the natural or legal person ('User') using the Platform. By accessing the Platform or using its services, the User declares that they have read, understood, and accepted all provisions of this agreement.",
        "termsServiceTitle": "2. Service Description",
        "termsServiceText": "The Platform provides an intermediary service for encrypted and instant file sharing between users. Shared files are not stored on Platform servers; they are only transmitted directly between users.",
        "termsConditionsTitle": "3. Terms of Use",
        "termsConditions1": "3.1. The User undertakes to use the Platform only for purposes that comply with the law.",
        "termsConditions2": "3.2. The User guarantees that all content shared through the Platform complies with the law and does not infringe the rights of third parties.",
        "termsConditions3": "3.3. The User will refrain from the following actions when using the Platform:",
        "termsConditionsItem1": "Sharing content that infringes copyright or other intellectual property rights",
        "termsConditionsItem2": "Sharing obscene, offensive, misleading, or illegal content",
        "termsConditionsItem3": "Sharing malware, viruses, or similar harmful content",
        "termsDisclaimerTitle": "4. Disclaimer",
        "termsDisclaimer1": "4.1. The Platform does not accept any responsibility for the accuracy, security, or legality of content shared by users.",
        "termsDisclaimer2": "4.2. The User is exclusively responsible for all transactions and shares made using the Platform.",
        "termsDisclaimer3": "4.3. The Platform does not guarantee that the service will be uninterrupted or error-free and cannot be held responsible for direct or indirect damages arising from the use of the service.",
        "termsIntellectualTitle": "5. Intellectual Property Rights",
        "termsIntellectualText": "All content, designs, software, and other materials on the Platform belong to the Platform and are protected by copyright laws. The User may not copy, distribute, or modify the Platform's software, design, or content without permission.",
        "termsModificationTitle": "6. Modification of the Agreement",
        "termsModificationText": "The Platform reserves the right to unilaterally change the provisions of this agreement at any time. The updated agreement takes effect on the date it is published on the Platform, and the User is deemed to have accepted the updated agreement by continuing to use the Platform.",
        "termsJurisdictionTitle": "7. Applicable Law and Jurisdiction",
        "termsJurisdictionText": "This agreement is subject to the laws of the Republic of Turkey. The parties accept that Istanbul (Çağlayan) Courts and Enforcement Offices have jurisdiction to resolve any disputes arising from this agreement.",
        
        "privacyTitle": "Privacy Policy",
        "privacyCollectionTitle": "1. Collected Data",
        "privacyCollectionText": "The Platform does not collect personal data to identify users. However, technical data such as IP addresses and connection times may be temporarily recorded for the provision of the service.",
        "privacyUseTitle": "2. Use of Data",
        "privacyUseText": "Collected technical data is used only to ensure the security of the service and to fulfill legal obligations. This data is not shared with third parties, sold, or used for commercial purposes.",
        "privacyStorageTitle": "3. Data Storage",
        "privacyStorageText": "Collected technical data is not stored for a specific period except for legal obligations and is regularly deleted.",
        "privacyThirdPartyTitle": "4. Third-Party Links",
        "privacyThirdPartyText": "The Platform may contain links to third-party websites. The Platform is not responsible for the privacy practices of these sites. Users should review the privacy policies of these sites.",
        
        // Terms Checkbox
        "termsCheckboxLabel": "I have read and agree to the Terms of Service and Privacy Policy",
        "termsLink": "Read Terms",
        "termsCheckboxRequired": "You must accept the Terms of Service to share files"
    },
    tr: {
        // Header
        "appTitle": "foxfile.org",
        "appDescription": "Güvenli uçtan uca şifreli dosya paylaşımı.",
        
        // Upload section
        "shareFile": "Dosya Paylaş",
        "selectFilePrompt": "Dosya seçmek için tıklayın veya sürükleyin",
        "selectedFile": "Seçilen dosya:",
        "shareButton": "Dosya Paylaş",
        "shareCode": "Paylaşım kodu:",
        "waitingForReceiver": "Alıcı bağlantısı bekleniyor...",
        "receiverConnected": "Alıcı bağlandı. Anahtar ve sinyal alışverişi yapılıyor...",
        "sendingFile": "Dosya gönderiliyor...",
        "fileSuccessfullySent": "Dosya başarıyla alıcıya iletildi!",
        "sendingProgress": "Gönderiliyor {percent}%...",
        
        // Download section
        "downloadFile": "Dosya İndir",
        "enterShareCode": "Paylaşım kodunu girin",
        "shareCodePlaceholder": "Örn: XYZ123",
        "connectAndDownload": "Bağlan ve İndir",
        "connecting": "Bağlantı kuruluyor...",
        "receivingFile": "Dosya alınıyor...",
        "transferComplete": "Dosya transferi tamamlandı!",
        "startDownload": "İndirmeyi Başlat",
        "downloadStarted": "İndirme otomatik olarak başladı",
        "clickToDownload": "Otomatik indirme başarısız. İndirmek için butona tıklayın.",
        "fileReceivedAssembling": "Dosya alındı. Birleştiriliyor...",
        "downloadButtonText": "{filename} İndir",
        "transferSuccessMessage": "'{filename}' dosyası başarıyla alındı!",
        
        // Info section
        "howItWorks": "Nasıl Çalışır?",
        "step1Title": "1. Dosya Seçimi & Kod",
        "step1Text": "Gönderici bir dosya seçer. Sunucu tarafından benzersiz bir paylaşım kodu oluşturulur.",
        "step2Title": "2. Kod Paylaşımı",
        "step2Text": "Gönderici, paylaşım kodunu alıcıya iletir.",
        "step3Title": "3. Güvenli Bağlantı",
        "step3Text": "Alıcı kodu girer. Sunucuya kurulan güvenli WebSocket bağlantısı iki kullanıcıyı eşleştirir.",
        "step4Title": "4. Güvenli P2P Aktarım",
        "step4Text": "Güvenli bağlantı kurulduktan sonra, şifrelenmiş dosya doğrudan cihazlar arasında (P2P) aktarılır.",
        "securityTitle": "Güvenlik",
        "securityText": "Dosyalar, WebRTC üzerinden aktarılmadan önce güvenli bir şekilde değiştirilen anahtar (AES-GCM) kullanılarak doğrudan tarayıcınızda şifrelenir. Yalnızca hedef alıcı şifreyi çözebilir. Sunucu bağlantıyı kolaylaştırır ancak dosya içeriğinizi veya şifre çözme anahtarını asla görmez. Meta veriler (dosya adı, boyutu) bağlantı kurulduktan *sonra* güvenli veri kanalı üzerinden şifresiz gönderilir.",
        "principleTitle": "Çalışma Prensibi",
        "principleText": "Diğer eşi bulmak için paylaşım kodunu kullanarak sunucumuza WebSocket üzerinden bağlanırsınız. Sunucu, güvenli anahtar değişimi (ECDH) ve WebRTC bağlantı kurulumu (STUN/TURN sunucuları kullanarak) için mesajları iletir. Güvenli WebRTC veri kanalı kurulduktan sonra, şifrelenmiş dosya doğrudan eşler arası aktarılır.",
        "technologiesTitle": "Neden Bağış Gerekli?",
        "technologiesText": "FoxFile, bağımsız bir geliştirici tarafından geliştirilmiştir ve tamamen ücretsizdir. Sunucu maliyetlerini karşılamak ve projeyi sürdürülebilir kılmak için desteğinize ihtiyacımız var.",
        
        // Footer
        "footerText": "foxfile.org © 2025 | Uçtan uca şifreli, eşler arası dosya paylaşım uygulaması",
        
        // Notifications
        "codeCopied": "Kod kopyalandı",
        "codeCreated": "Paylaşım kodu oluşturuldu",
        "pleaseSelectFile": "Lütfen bir dosya seçin",
        "invalidCodeFormat": "Geçersiz kod formatı",
        "connectionError": "Bağlantı hatası oluştu",
        "fileReadError": "Dosya okuma hatası",
        "scanQrCodePrompt": "İndirmek için taratınız",
        "downloadSuccessReceiver": "Dosya başarıyla indirildi!",
        // E2E Crypto & Connection Status (Turkish)
        "generatingCode": "Kod oluşturuluyor...",
        "connectingToSender": "Göndericiye bağlanılıyor...",
        "codeReceivedFromUrl": "Kod URL'den alındı, bağlanılıyor...",
        "keyGenerationError": "Şifreleme anahtarları oluşturulurken hata",
        "keyExchangeError": "Güvenli anahtar değişimi sırasında hata",
        "keyExchangeIncomplete": "Güvenli bağlantı hazır değil",
        "secureConnectionEstablishedSending": "Güvenli bağlantı kuruldu. Gönderime hazırlanılıyor...",
        "secureConnectionEstablishedWaiting": "Güvenli bağlantı kuruldu. Dosya bekleniyor...",
        "encryptionError": "Dosya şifreleme hatası",
        "decryptionError": "Dosya şifre çözme hatası",
        "downloadSetupError": "Dosya indirmeye hazırlanırken hata",
        "transferError": "Dosya aktarım hatası",
        "receiverConnectedInitiatingKeyExchange": "Alıcı bağlandı. Güvenli anahtar değişimi başlatılıyor...",
        "connectedToSenderInitiatingKeyExchange": "Göndericiye bağlandı. Güvenli anahtar değişimi başlatılıyor...",
        "downloadStarting": "İndirme başlatılıyor...",
        "fileSentWaitingConfirmation": "Dosya gönderildi. Alıcı onayı bekleniyor...",
        "transferSuccessPrompt": "Dosya başarıyla gönderildi! Tekrar paylaşmak için başka bir dosya seçin.",
        "transferStarted": "Dosya transferi başladı.",
        "channelsNotReady": "Veri kanalları henüz hazır değil.",
        "metadataError": "Meta veri işleme hatası.",
        "sendFileError": "Dosya gönderilemiyor. Önkoşullar sağlanmadı.",
        "chunkReadSendError": "Dosya parçası okuma veya gönderme hatası.",
        "fileSentWaiting": "Dosya gönderimi tamamlandı. Alıcı bekleniyor...",
        "transferAbortedChannelClose": "Kanal kapanması nedeniyle transfer iptal edildi.",
        "channelError": "Veri kanalı hatası",
        "transferAborted": "Dosya transferi iptal edildi.",
        "chunkDecryptError": "Dosya parçası şifre çözme hatası.",
        "receiveError": "Dosya parçası alma hatası.",
        "fileAssemblyError": "Alınan dosya birleştirilirken hata.",
        "connectionInterrupted": "Bağlantı kesildi.",
        "peerConnectionError": "Eş bağlantısı kurulamadı.",

        // Popup translations (Turkish)
        "successTitle": "Başarılı!",
        "okButton": "Tamam",
        // Donation Button (Turkish)
        "donateButton": "Destek Ol",
        "donateTooltipTitle": "Bu Projeyi Sevdiysen Destek Olabilirsin!",
        "donateTooltipLine1": "FoxFile, bağımsız bir geliştirici tarafından geliştirilmiştir ve tamamen ücretsizdir.",
        "donateTooltipLine2": "Sunucu maliyetlerini karşılamak ve projeyi sürdürülebilir kılmak için desteğinize ihtiyacımız var.",
        
        // Connection System Accordion
        "connectionSystemTitle": "Sistem Bağlantıları Nasıl Kurulur",
        "connectionSystemHowTitle": "Sistem Bağlantıları Nasıl Çalışır?",
        "sameNetworkTitle": "Aynı Yerel Ağda (LAN):",
        "sameNetworkText": "İki bilgisayar aynı yerel ağda (örneğin, aynı Wi-Fi) ise, STUN sunucuları IP adreslerinin keşfedilmesine yardımcı olur ve doğrudan bağlantı genellikle kolayca kurulabilir. Bu süreç şöyle işler:",
        "sameNetworkStep1": "Hem gönderici hem de alıcı, sunucumuza WebSocket üzerinden bağlanır.",
        "sameNetworkStep2": "Paylaşım kodu, eşleştirme için kullanılır.",
        "sameNetworkStep3": "STUN sunucularımız, her iki tarafın da yerel IP adreslerini keşfeder.",
        "sameNetworkStep4": "WebRTC bağlantısı kurulur ve dosya doğrudan eşler arasında aktarılır.",
        "differentNetworkTitle": "Farklı Ağlarda:",
        "differentNetworkText": "Bilgisayarlar farklı ağlarda ise (örneğin, farklı konumlarda, NAT arkasında veya güvenlik duvarları ile), bağlantı süreci daha karmaşıktır:",
        "differentNetworkStep1": "Sunucumuza WebSocket bağlantısı ve paylaşım kodu ile eşleştirme aynı şekilde çalışır.",
        "differentNetworkStep2": "STUN sunucuları önce doğrudan bağlantı kurmayı dener, ancak çoğu NAT cihazı ve güvenlik duvarı bunu engelleyebilir.",
        "differentNetworkStep3": "Doğrudan bağlantı kurulamazsa, TURN sunucularımız devreye girer.",
        "differentNetworkStep4": "TURN sunucuları, NAT ve güvenlik duvarlarını aşmak için bir rölesi olarak çalışır - iki taraf arasındaki iletişim bu sunucular üzerinden aktarılır.",
        "differentNetworkStep5": "Dosya transferi, TURN sunucularımız aracılığıyla gizli ve şifreli bir şekilde gerçekleşir.",
        "technicalDetailsTitle": "Teknik Detaylar:",
        "technicalDetailsText": "FoxFile, şu teknolojileri kullanarak güvenli bağlantıları sağlar:",
        "technicalDetailWebRTC": "WebRTC: Tarayıcı tabanlı gerçek zamanlı iletişim için",
        "technicalDetailSTUN": "STUN Sunucuları: NAT arkasındaki cihazların gerçek adreslerini keşfetmek için",
        "technicalDetailTURN": "TURN Sunucuları: Doğrudan bağlantı kurulamadığında trafiği yeniden yönlendirmek için",
        "technicalDetailDTLS": "DTLS: Veri kanalı için aktarım katmanı güvenliği",
        "technicalDetailAES": "AES-GCM: Dosya içeriğinin uçtan uca şifrelenmesi",
        "analyticsTitle": "Analitik:",
        "analyticsText": "Gizliliğe odaklı bir analitik aracı olan GoatCounter kullanıyoruz:",
        "analyticsNoCookies": "Çerez kullanılmaz",
        "analyticsAnonymous": "IP adresleri anonimleştirilerek ülke bazlı lokasyon bilgisi sağlanır",
        
        // Terms and Privacy
        "termsTitle": "Kullanıcı Sözleşmesi ve Gizlilik Politikası",
        "termsOfService": "Kullanıcı Sözleşmesi",
        "termsDate": "Yürürlük Tarihi: 20 Nisan 2025",
        "termsPartiesTitle": "1. Taraflar ve Kabul",
        "termsPartiesText": "Bu sözleşme, [Foxfile.org] ('Platform') ile Platform'u kullanan gerçek veya tüzel kişi ('Kullanıcı') arasında akdedilmiştir. Kullanıcı, Platform'a erişim sağlayarak veya hizmetleri kullanarak bu sözleşmenin tüm hükümlerini okuduğunu, anladığını ve kabul ettiğini beyan eder.",
        "termsServiceTitle": "2. Hizmetin Tanımı",
        "termsServiceText": "Platform, kullanıcılar arasında şifreli ve anlık dosya paylaşımı sağlayan bir aracı hizmet sunmaktadır. Paylaşılan dosyalar Platform sunucularında depolanmaz; yalnızca kullanıcılar arasında doğrudan iletilir.",
        "termsConditionsTitle": "3. Kullanım Koşulları",
        "termsConditions1": "3.1. Kullanıcı, Platform'u yalnızca yasalara uygun amaçlarla kullanmayı taahhüt eder.",
        "termsConditions2": "3.2. Kullanıcı, Platform üzerinden paylaştığı tüm içeriklerin yasalara uygun olduğunu ve üçüncü tarafların haklarını ihlal etmediğini garanti eder.",
        "termsConditions3": "3.3. Kullanıcı, Platform'u kullanırken aşağıdaki eylemlerden kaçınacaktır:",
        "termsConditionsItem1": "Telif hakkı veya diğer fikri mülkiyet haklarını ihlal eden içeriklerin paylaşılması",
        "termsConditionsItem2": "Müstehcen, saldırgan, yanıltıcı veya yasa dışı içeriklerin paylaşılması",
        "termsConditionsItem3": "Kötü amaçlı yazılım, virüs veya benzeri zararlı içeriklerin paylaşılması",
        "termsDisclaimerTitle": "4. Sorumluluk Reddi",
        "termsDisclaimer1": "4.1. Platform, kullanıcılar tarafından paylaşılan içeriklerin doğruluğu, güvenliği veya yasallığı konusunda herhangi bir sorumluluk kabul etmez.",
        "termsDisclaimer2": "4.2. Kullanıcı, Platform'u kullanarak gerçekleştirdiği tüm işlemlerden ve paylaşımlardan münhasıran sorumludur.",
        "termsDisclaimer3": "4.3. Platform, hizmetin kesintisiz veya hatasız olacağını garanti etmez ve hizmetin kullanımından doğabilecek doğrudan veya dolaylı zararlardan sorumlu tutulamaz.",
        "termsIntellectualTitle": "5. Fikri Mülkiyet Hakları",
        "termsIntellectualText": "Platform'da yer alan tüm içerikler, tasarımlar, yazılımlar ve diğer materyaller Platform'a aittir ve telif hakkı yasalarıyla korunmaktadır. Kullanıcı, Platform'un yazılımını, tasarımını veya içeriğini izinsiz olarak kopyalayamaz, dağıtamaz veya değiştiremez.",
        "termsModificationTitle": "6. Sözleşmenin Değiştirilmesi",
        "termsModificationText": "Platform, bu sözleşme hükümlerini dilediği zaman tek taraflı olarak değiştirme hakkını saklı tutar. Güncellenen sözleşme, Platform'da yayınlandığı tarihte yürürlüğe girer ve Kullanıcı, Platform'u kullanmaya devam ederek güncellenen sözleşmeyi kabul etmiş sayılır.",
        "termsJurisdictionTitle": "7. Uygulanacak Hukuk ve Yetki",
        "termsJurisdictionText": "Bu sözleşme, Türkiye Cumhuriyeti yasalarına tabidir. Taraflar, bu sözleşmeden doğabilecek her türlü uyuşmazlığın çözümünde İstanbul (Çağlayan) Mahkemeleri ve İcra Daireleri'nin yetkili olduğunu kabul eder.",
        
        "privacyTitle": "Gizlilik Politikası",
        "privacyCollectionTitle": "1. Toplanan Veriler",
        "privacyCollectionText": "Platform, kullanıcıların kimliklerini belirlemeye yönelik kişisel verileri toplamaz. Ancak, hizmetin sağlanabilmesi için IP adresleri ve bağlantı zamanları gibi teknik veriler geçici olarak kaydedilebilir.",
        "privacyUseTitle": "2. Verilerin Kullanımı",
        "privacyUseText": "Toplanan teknik veriler, yalnızca hizmetin güvenliğini sağlamak ve yasal yükümlülükleri yerine getirmek amacıyla kullanılır. Bu veriler, üçüncü taraflarla paylaşılmaz, satılmaz veya ticari amaçlarla kullanılmaz.",
        "privacyStorageTitle": "3. Verilerin Saklanması",
        "privacyStorageText": "Toplanan teknik veriler, yasal zorunluluklar dışında belirli bir süre saklanmaz ve düzenli olarak silinir.",
        "privacyThirdPartyTitle": "4. Üçüncü Taraf Bağlantıları",
        "privacyThirdPartyText": "Platform, üçüncü taraf web sitelerine bağlantılar içerebilir. Bu sitelerin gizlilik uygulamalarından Platform sorumlu değildir. Kullanıcılar, bu sitelerin gizlilik politikalarını incelemelidir.",
        
        // Terms Checkbox
        "termsCheckboxLabel": "Kullanıcı Sözleşmesi ve Gizlilik Politikası'nı okudum ve kabul ediyorum",
        "termsLink": "Sözleşmeyi Oku",
        "termsCheckboxRequired": "Dosya paylaşmak için Kullanıcı Sözleşmesi'ni kabul etmelisiniz"
    }
};

// Theme configuration
const themes = {
    light: {
        backgroundColor: "#f9fafb",
        cardBackgroundColor: "#ffffff",
        textColor: "#111827",
        secondaryTextColor: "#4b5563",
        accentColor: "#4f46e5",
        accentHoverColor: "#4338ca",
        borderColor: "#e5e7eb",
        inputBackgroundColor: "#f9fafb",
        successColor: "#10b981",
        successHoverColor: "#059669",
        errorColor: "#ef4444",
        infoBackgroundColor: "#f3f4f6"
    },
    dark: {
        backgroundColor: "#111827",
        cardBackgroundColor: "#1f2937",
        textColor: "#f9fafb",
        secondaryTextColor: "#d1d5db",
        accentColor: "#6366f1",
        accentHoverColor: "#4f46e5",
        borderColor: "#374151",
        inputBackgroundColor: "#374151",
        successColor: "#10b981",
        successHoverColor: "#059669",
        errorColor: "#ef4444",
        infoBackgroundColor: "#374151"
    }
};

// Get user's preferred language
function getPreferredLanguage() {
    // Check if language is stored in localStorage
    const storedLang = localStorage.getItem('preferredLanguage');
    if (storedLang && translations[storedLang]) {
        return storedLang;
    }
    
    // Check browser language
    const browserLang = navigator.language.split('-')[0];
    return browserLang === 'tr' ? 'tr' : 'en';
}

// Get user's preferred theme
function getPreferredTheme() {
    // Check if theme is stored in localStorage
    const storedTheme = localStorage.getItem('preferredTheme');
    if (storedTheme && (storedTheme === 'light' || storedTheme === 'dark')) {
        return storedTheme;
    }
    
    // Check system preference
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
        return 'dark';
    }
    
    return 'light';
}

// Set language
function setLanguage(lang) {
    if (!translations[lang]) {
        lang = 'en';
    }
    
    localStorage.setItem('preferredLanguage', lang);
    document.documentElement.setAttribute('lang', lang);
    
    // Update all text elements with translations
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[lang][key]) {
            element.textContent = translations[lang][key];
        }
    });
    
    // Update placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(element => {
        const key = element.getAttribute('data-i18n-placeholder');
        if (translations[lang][key]) {
            element.setAttribute('placeholder', translations[lang][key]);
        }
    });
}

// Set theme
function setTheme(theme) {
    if (!themes[theme]) {
        theme = 'light';
    }
    
    localStorage.setItem('preferredTheme', theme);
    document.documentElement.setAttribute('data-theme', theme);
    
    // Apply theme colors to CSS variables
    const root = document.documentElement;
    Object.entries(themes[theme]).forEach(([property, value]) => {
        root.style.setProperty(`--${property}`, value);
    });
}

// Toggle language
function toggleLanguage() {
    const currentLang = localStorage.getItem('preferredLanguage') || getPreferredLanguage();
    const newLang = currentLang === 'tr' ? 'en' : 'tr';
    setLanguage(newLang);
}

// Toggle theme
function toggleTheme() {
    const currentTheme = localStorage.getItem('preferredTheme') || getPreferredTheme();
    const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
    setTheme(newTheme);
}

// Initialize language and theme
function initializeSettings() {
    const preferredLanguage = getPreferredLanguage();
    const preferredTheme = getPreferredTheme();
    
    setLanguage(preferredLanguage);
    setTheme(preferredTheme);
    
    // Listen for system theme changes
    if (window.matchMedia) {
        window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
            // Only change theme if user hasn't manually set a preference
            if (!localStorage.getItem('preferredTheme')) {
                setTheme(e.matches ? 'dark' : 'light');
            }
        });
    }
}

// --- Start: Added RTC Configuration Function ---
async function getRTCConfiguration() {
    console.log("Fetching TURN credentials from server...");
    try {
        const response = await fetch('/api/turn-credentials');
        if (!response.ok) {
            throw new Error(`Server responded with ${response.status}`);
        }
        const credentials = await response.json();
        console.log("Received TURN credentials:", credentials.username);

        const configuration = {
            iceServers: [
                // Önce STUN sunucuları (opsiyonel ama önerilir)
                { urls: 'stun:stun.l.google.com:19302' },
                { urls: 'stun:stun1.l.google.com:19302' },
                
                // Sunucudan alınan dinamik TURN bilgileri
                {
                    urls: [
                        `turn:foxfile.org:3478?transport=udp`,
                        `turn:foxfile.org:3478?transport=tcp`
                    ],
                    username: credentials.username,
                    credential: credentials.credential
                }
            ]
        };
        return configuration;

    } catch (error) {
        console.error("Failed to fetch TURN credentials, falling back to STUN only:", error);
        // Hata durumunda sadece STUN ile devam et
        return {
            iceServers: [
                { urls: 'stun:stun.l.google.com:19302' },
                { urls: 'stun:stun1.l.google.com:19302' },
            ]
        };
    }
}
// --- End: Added RTC Configuration Function ---

// Expose functions and data to the global scope via window.appConfig
window.appConfig = {
    translations,
    themes,
    getPreferredLanguage,
    getPreferredTheme,
    setLanguage,
    setTheme,
    toggleLanguage,
    toggleTheme,
    initializeSettings,
    getRTCConfiguration
};